name: "live-video-sync"
services:
  postgres:
    image: postgres:17.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8001:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      start_period: 120s
      interval: 10s

volumes:
  postgres-data:
  logs:
